title: Audra Blue
description: American Staffordshire Terrier
url: http://audra.blue
avatar: /assets/img/audraAvatar.jpg
favicon: /assets/img/favicon.ico
google_analytics: 
disqus_shortname: 

about:
  - paragraph: Audra Blue is an American Staffordshire Terrier in Portland Oregon.
    text_align: center
    # links:
    #   - name: Lang Liu
    #     url: http://kkninjae.com/about/
    #     external: false
    #   - name: Design
    #     url: https://github.com/kkninjae/book
    #     external: true
    
