title: Audra Blue
description: American Staffordshire Terrier
url: http://www.audra.blue
avatar: /book/assets/img/blueball_avatar.jpg
favicon: /assets/img/favicon.ico
google_analytics: 
disqus_shortname: 

about:
  - paragraph: ?link?, a simple Jekyll theme. Built by ?link?
    text_align: center
    links:
      - name: Book
        url: https://github.com/kkninjae/book
        external: true
      - name: Lang Liu
        url: http://kkninjae.com/about/
        external: false

    
